Import('rtconfig')
import os
from building import *

Import('SDK_ROOT')
Import('APP_ROOT')

cwd = GetCurrentDir()
path_inc = [APP_ROOT + '/common/inc']
path_inc += [APP_ROOT + '/include']
path_inc += [SDK_ROOT + '/extlib/inc']
path_inc += [SDK_ROOT + '/extlib']
path_inc += [SDK_ROOT + '/extlib/inc/isp']
path_inc += [SDK_ROOT]

e_inc = [SDK_ROOT + '/components/sensor']
CPPPATH = [cwd]
src = Glob('*.c')


group = DefineGroup('config', src, depend = [''], CPPPATH = CPPPATH, LOCAL_CPPPATH = path_inc)
Return('group')
